// ---------------------------------------------------------------------------
//
//                   University of Wisconsin-Stout
//            Mathematics, Statistics & Computer Science
//                 CS-244 Data Structures - Fall 2016
//
// This software is student work for CSS-244 Data Structures and may not
// be copied except by the original author and instructor.
// Copyright 2016
//
// Stoutonian.h
//
// The Stoutonian class for creating a Stoutonian object; names are randomly-
// generated by the Names.h class
//
// Instructor: Jocelyn Richardt
// Assignment: StoutonianGame
// Author: Luke A Chase
// Date: 03/01/2017
//
// ---------------------------------------------------------------------------

#ifndef STOUTONIAN_H
#define STOUTONIAN_H

using namespace std;

class Stoutonian
{
    public:
        struct Range
        {
            public:
                int low;
                int high;
        };

        Stoutonian();
        Stoutonian(string name, int sharpness, int strength, int speed);
        virtual ~Stoutonian();

        string getName() { return m_Name; }
        void setName(string val) { m_Name = val; }
        int getInitialMentalSharpness() { return m_InitialMentalSharpness; }
        void setInitialMentalSharpness(int val) { m_InitialMentalSharpness = val; }
        int getActualMentalSharpness() { return m_ActualMentalSharpness; }
        void setActualMentalSharpness(int val) { m_ActualMentalSharpness = val; }
        int getChallengeStrength() { return m_ChallengeStrength; }
        void setChallengeStrength(int val) { m_ChallengeStrength = val; }
        int getSpeed() { return m_Speed; }
        void setSpeed(int val) { m_Speed = val; }
        Range getRange() { return m_Range; }
        void setRange(int low, int high) { m_Range.low = low; m_Range.high = high; }

        void speak();
        void rest();
        bool runAway();
        void challenge(Stoutonian& opponent);
        bool recruit(Stoutonian& opponent);

    protected:

    private:
        string m_Name;
        int m_InitialMentalSharpness;
        int m_ActualMentalSharpness;
        int m_ChallengeStrength;
        int m_Speed;
        Range m_Range;
};

#endif // STOUTONIAN_H
